#!/usr/bin/env -S CARGO_TARGET_DIR=target/check-layout-boundaries-script nix shell "github:nix-community/fenix?rev=092bd452904e749efa39907aa4a20a42678ac31e#minimal.toolchain" nixpkgs#gcc -c cargo -q -Zscript

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const ROOT_FLAG: &str = "--root";
const SELF_TEST_FLAG: &str = "--self-test";
const DEFAULT_ROOT: &str = ".";
const AGENTS_PATH: &str = "AGENTS.md";
const README_PATH: &str = "README.md";
const ARCHITECTURE_PATH: &str = "docs/architecture.md";
const CHECKLIST_PATH: &str = "docs/layout-checklist.md";
const STEVENARELLA_AGENTS_PATH: &str = "clients/stevenarella/AGENTS.md";
const VALENCE_AGENTS_PATH: &str = "servers/valence/AGENTS.md";
const HYPERION_GIT_PATH: &str = "hyperion/.git";
const LEAFISH_GIT_PATH: &str = "Leafish/.git";
const STEVENARELLA_LABEL: &str = "clients/stevenarella/";
const VALENCE_LABEL: &str = "servers/valence/";
const LEAFISH_LABEL: &str = "Leafish/";
const HYPERION_LABEL: &str = "hyperion/";
const REFERENCE_ONLY_TEXT: &str = "reference-only";
const NESTED_GIT_TEXT: &str = "nested Git";
const DEFAULT_GATE_EXCLUSION_TEXT: &str = "excluded from default compatibility gates";
const OPT_IN_TEXT: &str = "explicit opt-in";
const PARENT_STATUS_TEXT: &str = "parent repo status";
const LEAFISH_WAIVER_TEXT: &str = "Waived here because the nested checkout is not parent-owned";
const SUCCESS_MESSAGE: &str = "layout boundary checks passed";
const SELF_TEST_SUCCESS_MESSAGE: &str = "layout boundary self-test passed";
const SUCCESS: ExitCode = ExitCode::SUCCESS;
const FAILURE: ExitCode = ExitCode::FAILURE;
const PATH_SEPARATOR: char = '/';
const ROOT_PATH_SUFFIX: &str = "/";
const GIT_BOUNDARY_SUFFIX: &str = "/.git";
const GIT_ENTRY_NAME: &str = ".git";
const RESULT_LINK_NAME: &str = "result";
const RESULT_LINK_PREFIX: &str = "result-";
const TARGET_DIR_NAME: &str = "target";
const TARGET_LOG_PREFIX: &str = "target-";
const LOG_SUFFIX: &str = ".log";
const RUN_LOG_SUFFIX: &str = ".run.log";
const GENERATED_RUST_PATH: &str = "compat/runner/src/scenario_manifest_generated.rs";
const GENERATED_INDEX_PATH: &str = "docs/evidence/mc-compat-scenario-index.generated.md";
const GENERATED_RUST_MARKER: &str =
    "// @generated by tools/check_scenario_manifest.rs --write-generated-surfaces";
const GENERATED_INDEX_MARKER: &str = "<!-- @generated by tools/check_scenario_manifest.rs --write-generated-surfaces; edit compat/config/scenario-manifest.ncl instead. -->";
const GENERATED_OWNER_HINT: &str = "run tools/check_scenario_manifest.rs --write-generated-surfaces after editing compat/config/scenario-manifest.ncl";
const REGISTRY_PATH_CELL_INDEX: usize = 0;
const REGISTRY_ROLE_CELL_INDEX: usize = 1;
const REGISTRY_OWNERSHIP_CELL_INDEX: usize = 2;
const REGISTRY_LOCAL_NOTES_CELL_INDEX: usize = 3;
const REGISTRY_DEFAULT_GATES_CELL_INDEX: usize = 4;
const REGISTRY_EXPECTED_CELL_COUNT: usize = 5;
const FIRST_PATH_SEGMENT_LIMIT: usize = 2;
const REQUIRED: Severity = Severity::Required;
const ADVISORY: Severity = Severity::Advisory;

const ALLOWED_ROOT_FILES: &[&str] = &[
    ".envrc",
    ".gitignore",
    AGENTS_PATH,
    README_PATH,
    "flake.lock",
    "flake.nix",
];

const IGNORED_WALK_DIRS: &[&str] = &[".agent", ".direnv", ".git", ".pi"];

const REQUIRED_CONTRACT_PHRASES: &[&str] = &[
    "Layout guard contract",
    "Diagnostic classes",
    "Waiver model",
    "Source-of-truth inputs",
    "Non-claims",
    "Artifact classes",
    "Durable evidence",
    "Generated checked-in output",
    "Transient run/build output",
    "Local scratch",
    "undocumented_root_directory",
    "undocumented_nested_git",
    "root_transient_artifact",
    "missing_subtree_documentation",
    "generated_marker_drift",
    "component_registry_mismatch",
    "does not claim live compatibility, semantic parity, production readiness, public-server safety, or evidence correctness outside layout policy",
];

#[derive(Debug, Clone)]
struct LayoutDocs {
    agents: String,
    readme: String,
    architecture: String,
    checklist: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EntryKind {
    Directory,
    File,
    Symlink,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TreeEntry {
    path: String,
    kind: EntryKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct RegistryEntry {
    path: String,
    role: String,
    ownership: String,
    local_notes: String,
    default_gates: String,
}

#[derive(Debug, Clone)]
struct RepositoryModel {
    docs: LayoutDocs,
    tree: Vec<TreeEntry>,
    generated_text: BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct GeneratedSurfaceRule {
    path: &'static str,
    marker: &'static str,
    owner_hint: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct LayoutRules {
    generated_surfaces: Vec<GeneratedSurfaceRule>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Severity {
    Advisory,
    Required,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Diagnostic {
    code: &'static str,
    severity: Severity,
    path: String,
    rule: &'static str,
    message: String,
    owner_or_waiver_hint: String,
    next_action: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct GuardReport {
    diagnostics: Vec<Diagnostic>,
}

fn contains_all(text: &str, needles: &[&str]) -> bool {
    needles.iter().all(|needle| text.contains(needle))
}

fn missing_items<'a>(text: &str, items: &'a [&str]) -> Vec<&'a str> {
    items
        .iter()
        .copied()
        .filter(|item| !text.contains(item))
        .collect()
}

fn push_missing_doc(
    diagnostics: &mut Vec<Diagnostic>,
    code: &'static str,
    path: &str,
    needs: &[&str],
) {
    if needs.is_empty() {
        return;
    }

    diagnostics.push(Diagnostic {
        code,
        severity: REQUIRED,
        path: path.to_string(),
        rule: "missing_subtree_documentation",
        message: format!("{path} must mention: {}", needs.join(", ")),
        owner_or_waiver_hint: String::from("update root layout docs or record an explicit waiver"),
        next_action: String::from("edit AGENTS.md, README.md, docs/architecture.md, or docs/layout-checklist.md so the boundary is reviewable"),
    });
}

fn diagnostic(
    code: &'static str,
    severity: Severity,
    path: impl Into<String>,
    rule: &'static str,
    message: impl Into<String>,
    owner_or_waiver_hint: impl Into<String>,
    next_action: impl Into<String>,
) -> Diagnostic {
    Diagnostic {
        code,
        severity,
        path: path.into(),
        rule,
        message: message.into(),
        owner_or_waiver_hint: owner_or_waiver_hint.into(),
        next_action: next_action.into(),
    }
}

fn default_rules() -> LayoutRules {
    LayoutRules {
        generated_surfaces: vec![
            GeneratedSurfaceRule {
                path: GENERATED_RUST_PATH,
                marker: GENERATED_RUST_MARKER,
                owner_hint: GENERATED_OWNER_HINT,
            },
            GeneratedSurfaceRule {
                path: GENERATED_INDEX_PATH,
                marker: GENERATED_INDEX_MARKER,
                owner_hint: GENERATED_OWNER_HINT,
            },
        ],
    }
}

fn validate_layout(model: &RepositoryModel, rules: &LayoutRules) -> GuardReport {
    let registry = parse_component_registry(&model.docs.checklist);
    let mut diagnostics = Vec::new();

    diagnostics.extend(check_guard_contract(&model.docs.checklist));
    diagnostics.extend(check_legacy_layout_docs(&model.docs, &model.tree));
    diagnostics.extend(check_component_registry(&model.tree, &registry));
    diagnostics.extend(check_root_entries(&model.tree, &registry));
    diagnostics.extend(check_nested_git(&model.tree, &registry));
    diagnostics.extend(check_generated_surfaces(&model.generated_text, rules));

    diagnostics.sort_by(|left, right| {
        left.severity
            .cmp(&right.severity)
            .then_with(|| left.code.cmp(right.code))
            .then_with(|| left.path.cmp(&right.path))
    });

    GuardReport { diagnostics }
}

fn check_guard_contract(checklist: &str) -> Vec<Diagnostic> {
    let missing = missing_items(checklist, REQUIRED_CONTRACT_PHRASES);
    if missing.is_empty() {
        Vec::new()
    } else {
        vec![diagnostic(
            "missing_layout_guard_contract",
            REQUIRED,
            CHECKLIST_PATH,
            "layout_guard_contract",
            format!(
                "{} is missing guard contract terms: {}",
                CHECKLIST_PATH,
                missing.join(", ")
            ),
            "docs/layout-checklist.md owns the layout guard contract",
            "document diagnostic classes, waiver model, source-of-truth inputs, and non-claims",
        )]
    }
}

fn check_legacy_layout_docs(docs: &LayoutDocs, tree: &[TreeEntry]) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();

    if !tree_contains_path(tree, STEVENARELLA_AGENTS_PATH) {
        push_missing_doc(
            &mut diagnostics,
            "missing_stevenarella_agents",
            STEVENARELLA_AGENTS_PATH,
            &["local agent notes for the core client"],
        );
    }

    if !tree_contains_path(tree, VALENCE_AGENTS_PATH) {
        push_missing_doc(
            &mut diagnostics,
            "missing_valence_agents",
            VALENCE_AGENTS_PATH,
            &["local agent notes for the core server"],
        );
    }

    if !contains_all(
        &docs.agents,
        &[
            STEVENARELLA_AGENTS_PATH,
            VALENCE_AGENTS_PATH,
            CHECKLIST_PATH,
        ],
    ) {
        push_missing_doc(
            &mut diagnostics,
            "agents_local_notes_links",
            AGENTS_PATH,
            &[
                STEVENARELLA_AGENTS_PATH,
                VALENCE_AGENTS_PATH,
                CHECKLIST_PATH,
            ],
        );
    }

    if !contains_all(
        &docs.readme,
        &[
            STEVENARELLA_AGENTS_PATH,
            VALENCE_AGENTS_PATH,
            CHECKLIST_PATH,
        ],
    ) {
        push_missing_doc(
            &mut diagnostics,
            "readme_local_notes_links",
            README_PATH,
            &[
                STEVENARELLA_AGENTS_PATH,
                VALENCE_AGENTS_PATH,
                CHECKLIST_PATH,
            ],
        );
    }

    if !contains_all(
        &docs.architecture,
        &[
            STEVENARELLA_AGENTS_PATH,
            VALENCE_AGENTS_PATH,
            CHECKLIST_PATH,
        ],
    ) {
        push_missing_doc(
            &mut diagnostics,
            "architecture_local_notes_links",
            ARCHITECTURE_PATH,
            &[
                STEVENARELLA_AGENTS_PATH,
                VALENCE_AGENTS_PATH,
                CHECKLIST_PATH,
            ],
        );
    }

    if !contains_all(
        &docs.checklist,
        &[
            STEVENARELLA_LABEL,
            VALENCE_LABEL,
            STEVENARELLA_AGENTS_PATH,
            VALENCE_AGENTS_PATH,
        ],
    ) {
        push_missing_doc(
            &mut diagnostics,
            "checklist_local_notes_inventory",
            CHECKLIST_PATH,
            &[
                STEVENARELLA_LABEL,
                VALENCE_LABEL,
                STEVENARELLA_AGENTS_PATH,
                VALENCE_AGENTS_PATH,
            ],
        );
    }

    if tree_contains_path(tree, LEAFISH_GIT_PATH)
        && !contains_all(
            &docs.agents,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                NESTED_GIT_TEXT,
                PARENT_STATUS_TEXT,
            ],
        )
    {
        push_missing_doc(
            &mut diagnostics,
            "agents_leafish_boundary",
            AGENTS_PATH,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                NESTED_GIT_TEXT,
                PARENT_STATUS_TEXT,
            ],
        );
    }

    if tree_contains_path(tree, LEAFISH_GIT_PATH)
        && !contains_all(
            &docs.readme,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                DEFAULT_GATE_EXCLUSION_TEXT,
                OPT_IN_TEXT,
            ],
        )
    {
        push_missing_doc(
            &mut diagnostics,
            "readme_leafish_boundary",
            README_PATH,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                DEFAULT_GATE_EXCLUSION_TEXT,
                OPT_IN_TEXT,
            ],
        );
    }

    if tree_contains_path(tree, LEAFISH_GIT_PATH)
        && !contains_all(
            &docs.architecture,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                NESTED_GIT_TEXT,
                CHECKLIST_PATH,
            ],
        )
    {
        push_missing_doc(
            &mut diagnostics,
            "architecture_leafish_boundary",
            ARCHITECTURE_PATH,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                NESTED_GIT_TEXT,
                CHECKLIST_PATH,
            ],
        );
    }

    if tree_contains_path(tree, LEAFISH_GIT_PATH)
        && !contains_all(
            &docs.checklist,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                LEAFISH_WAIVER_TEXT,
                "Excluded from default gates unless explicitly selected",
            ],
        )
    {
        push_missing_doc(
            &mut diagnostics,
            "checklist_leafish_boundary",
            CHECKLIST_PATH,
            &[
                LEAFISH_LABEL,
                REFERENCE_ONLY_TEXT,
                LEAFISH_WAIVER_TEXT,
                "Excluded from default gates unless explicitly selected",
            ],
        );
    }

    if tree_contains_path(tree, HYPERION_GIT_PATH)
        && !contains_all(
            &docs.checklist,
            &[HYPERION_LABEL, "independent", "separate jj/git workflow"],
        )
    {
        push_missing_doc(
            &mut diagnostics,
            "checklist_hyperion_boundary",
            CHECKLIST_PATH,
            &[HYPERION_LABEL, "independent", "separate jj/git workflow"],
        );
    }

    diagnostics
}

fn parse_component_registry(checklist: &str) -> Vec<RegistryEntry> {
    let mut entries = Vec::new();
    for line in checklist.lines() {
        let trimmed = line.trim();
        if !trimmed.starts_with('|') || trimmed.contains("---") || trimmed.contains("Path | Role") {
            continue;
        }

        let cells = trimmed
            .trim_matches('|')
            .split('|')
            .map(|cell| cell.trim().to_string())
            .collect::<Vec<_>>();
        if cells.len() < REGISTRY_EXPECTED_CELL_COUNT {
            continue;
        }

        let Some(path) = extract_first_backticked_path(&cells[REGISTRY_PATH_CELL_INDEX]) else {
            continue;
        };

        entries.push(RegistryEntry {
            path,
            role: cells[REGISTRY_ROLE_CELL_INDEX].clone(),
            ownership: cells[REGISTRY_OWNERSHIP_CELL_INDEX].clone(),
            local_notes: cells[REGISTRY_LOCAL_NOTES_CELL_INDEX].clone(),
            default_gates: cells[REGISTRY_DEFAULT_GATES_CELL_INDEX].clone(),
        });
    }
    entries
}

fn extract_first_backticked_path(text: &str) -> Option<String> {
    let (_, after_open) = text.split_once('`')?;
    let (path, _) = after_open.split_once('`')?;
    if path.ends_with(ROOT_PATH_SUFFIX) {
        Some(path.to_string())
    } else {
        None
    }
}

fn extract_backticked_paths(text: &str) -> Vec<String> {
    let mut paths = Vec::new();
    let mut rest = text;
    while let Some((_, after_open)) = rest.split_once('`') {
        let Some((candidate, after_close)) = after_open.split_once('`') else {
            break;
        };
        if is_relative_doc_path(candidate) {
            paths.push(candidate.to_string());
        }
        rest = after_close;
    }
    paths
}

fn is_relative_doc_path(path: &str) -> bool {
    !path.is_empty()
        && !path.starts_with(PATH_SEPARATOR)
        && !path.ends_with(ROOT_PATH_SUFFIX)
        && !path.contains("..")
}

fn check_component_registry(tree: &[TreeEntry], registry: &[RegistryEntry]) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    for entry in registry {
        let component_observed = tree_contains_path(tree, trim_root_suffix(&entry.path));
        let parent_owned = is_parent_owned(entry);
        if parent_owned && !component_observed {
            diagnostics.push(diagnostic(
                "component_registry_mismatch",
                REQUIRED,
                entry.path.clone(),
                "component_registry_mismatch",
                format!("parent-owned registry path {} is missing from the modeled tree", entry.path),
                "component registry rows in docs/layout-checklist.md are authoritative for parent-owned roots",
                "restore the component root or change the registry row with a reviewable waiver",
            ));
            continue;
        }

        if parent_owned
            && tree_contains_path(
                tree,
                &format!("{}{}", trim_root_suffix(&entry.path), GIT_BOUNDARY_SUFFIX),
            )
        {
            diagnostics.push(diagnostic(
                "component_registry_mismatch",
                REQUIRED,
                entry.path.clone(),
                "component_registry_mismatch",
                format!("parent-owned registry path {} contains a nested Git boundary", entry.path),
                "parent-owned core component trees use the parent repository status",
                "remove the nested checkout or reclassify the registry row before treating it as parent-owned",
            ));
        }

        if should_check_local_notes(entry, component_observed) {
            for note_path in extract_backticked_paths(&entry.local_notes) {
                if !tree_contains_path(tree, &note_path) {
                    diagnostics.push(diagnostic(
                        "missing_subtree_documentation",
                        REQUIRED,
                        note_path.clone(),
                        "missing_subtree_documentation",
                        format!("registry path {} lists missing local note {}", entry.path, note_path),
                        "local-note paths listed in docs/layout-checklist.md are guard inputs",
                        "add the local note file or replace the local-note cell with an explicit waiver",
                    ));
                }
            }
        }
    }
    diagnostics
}

fn should_check_local_notes(entry: &RegistryEntry, component_observed: bool) -> bool {
    (component_observed || is_parent_owned(entry)) && !has_local_note_waiver(entry)
}

fn is_parent_owned(entry: &RegistryEntry) -> bool {
    entry.ownership.contains("Parent repository owned")
}

fn has_local_note_waiver(entry: &RegistryEntry) -> bool {
    let combined =
        format!("{} {} {}", entry.role, entry.ownership, entry.local_notes).to_ascii_lowercase();
    combined.contains("waived") || combined.contains("waiver")
}

fn check_root_entries(tree: &[TreeEntry], registry: &[RegistryEntry]) -> Vec<Diagnostic> {
    let documented_roots = documented_root_names(registry);
    let mut diagnostics = Vec::new();

    for entry in root_entries(tree) {
        if is_allowed_root_file(&entry.path) || is_hidden_root_entry(&entry.path) {
            continue;
        }
        if is_transient_root_artifact(&entry.path) {
            diagnostics.push(diagnostic(
                "root_transient_artifact",
                ADVISORY,
                entry.path.clone(),
                "root_transient_artifact",
                format!("root transient artifact {} should stay scratch-only", entry.path),
                "transient root artifacts are advisory unless cited as review evidence",
                "move review-critical output under docs/evidence/ with a BLAKE3 manifest, otherwise leave it ignored or clean it locally",
            ));
            continue;
        }
        if entry.kind == EntryKind::Directory && !documented_roots.contains(&entry.path) {
            diagnostics.push(diagnostic(
                "undocumented_root_directory",
                REQUIRED,
                entry.path.clone(),
                "undocumented_root_directory",
                format!("root directory {} is absent from docs/layout-checklist.md", entry.path),
                "docs/layout-checklist.md is the component registry and root allowlist",
                "document the root directory with ownership/default-gate policy or remove the accidental directory",
            ));
        }
    }

    diagnostics
}

fn root_entries(tree: &[TreeEntry]) -> Vec<&TreeEntry> {
    tree.iter()
        .filter(|entry| !entry.path.contains(PATH_SEPARATOR))
        .collect()
}

fn documented_root_names(registry: &[RegistryEntry]) -> BTreeSet<String> {
    registry
        .iter()
        .filter_map(|entry| first_path_segment(&entry.path))
        .collect()
}

fn first_path_segment(path: &str) -> Option<String> {
    path.splitn(FIRST_PATH_SEGMENT_LIMIT, PATH_SEPARATOR)
        .next()
        .filter(|segment| !segment.is_empty())
        .map(ToString::to_string)
}

fn is_allowed_root_file(path: &str) -> bool {
    ALLOWED_ROOT_FILES.iter().any(|allowed| path == *allowed)
}

fn is_hidden_root_entry(path: &str) -> bool {
    path.starts_with('.')
}

fn is_transient_root_artifact(path: &str) -> bool {
    path == RESULT_LINK_NAME
        || path.starts_with(RESULT_LINK_PREFIX)
        || path == TARGET_DIR_NAME
        || (path.starts_with(TARGET_LOG_PREFIX) && path.ends_with(LOG_SUFFIX))
        || path.ends_with(RUN_LOG_SUFFIX)
}

fn check_nested_git(tree: &[TreeEntry], registry: &[RegistryEntry]) -> Vec<Diagnostic> {
    let allowed = allowed_nested_git_roots(registry);
    let mut diagnostics = Vec::new();

    for entry in tree.iter().filter(|entry| is_git_boundary(&entry.path)) {
        let Some(owner_root) = git_boundary_owner_root(&entry.path) else {
            continue;
        };
        if !allowed.contains(&owner_root) {
            diagnostics.push(diagnostic(
                "undocumented_nested_git",
                REQUIRED,
                owner_root.clone(),
                "undocumented_nested_git",
                format!("nested Git boundary {} is not a documented exception", entry.path),
                "nested Git exceptions must be listed in docs/layout-checklist.md or the component registry",
                "classify the checkout as parent-owned, reference-only, or external before relying on it",
            ));
        }
    }

    diagnostics
}

fn allowed_nested_git_roots(registry: &[RegistryEntry]) -> BTreeSet<String> {
    registry
        .iter()
        .filter(|entry| expects_nested_git(entry))
        .map(|entry| trim_root_suffix(&entry.path).to_string())
        .collect()
}

fn expects_nested_git(entry: &RegistryEntry) -> bool {
    let combined = format!("{} {} {}", entry.role, entry.ownership, entry.local_notes);
    combined.contains("Nested repo")
        || combined.contains("nested Git")
        || combined.contains("nested checkout")
        || combined.contains("separate jj/git workflow")
}

fn is_git_boundary(path: &str) -> bool {
    path == GIT_ENTRY_NAME || path.ends_with(GIT_BOUNDARY_SUFFIX)
}

fn git_boundary_owner_root(path: &str) -> Option<String> {
    path.strip_suffix(GIT_BOUNDARY_SUFFIX)
        .map(ToString::to_string)
}

fn check_generated_surfaces(
    generated_text: &BTreeMap<String, String>,
    rules: &LayoutRules,
) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    for surface in &rules.generated_surfaces {
        match generated_text.get(surface.path) {
            Some(text) if text.contains(surface.marker) => {}
            Some(_) => diagnostics.push(diagnostic(
                "generated_marker_drift",
                REQUIRED,
                surface.path,
                "generated_marker_drift",
                format!("generated surface {} is missing marker {:?}", surface.path, surface.marker),
                surface.owner_hint,
                "refresh generated surfaces or restore the ownership marker before editing by hand",
            )),
            None => diagnostics.push(diagnostic(
                "generated_marker_drift",
                REQUIRED,
                surface.path,
                "generated_marker_drift",
                format!("generated surface {} is missing from the modeled tree", surface.path),
                surface.owner_hint,
                "restore the generated surface or update the guard rule with a reviewed source-of-truth change",
            )),
        }
    }
    diagnostics
}

fn tree_contains_path(tree: &[TreeEntry], path: &str) -> bool {
    tree.iter().any(|entry| entry.path == path)
}

fn trim_root_suffix(path: &str) -> &str {
    path.trim_end_matches(ROOT_PATH_SUFFIX)
}

fn report_has_required_findings(report: &GuardReport) -> bool {
    report
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.severity == REQUIRED)
}

fn render_success(report: &GuardReport) -> String {
    let advisory_count = report
        .diagnostics
        .iter()
        .filter(|diagnostic| diagnostic.severity == ADVISORY)
        .count();
    if advisory_count == 0 {
        String::from(SUCCESS_MESSAGE)
    } else {
        format!(
            "{SUCCESS_MESSAGE}; advisory_findings={advisory_count}\n{}",
            render_diagnostics(report)
        )
    }
}

fn render_diagnostics(report: &GuardReport) -> String {
    report
        .diagnostics
        .iter()
        .map(render_diagnostic)
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_diagnostic(diagnostic: &Diagnostic) -> String {
    format!(
        "severity={:?} code={} path={} rule={} message={} owner_or_waiver_hint={} next_action={}",
        diagnostic.severity,
        diagnostic.code,
        diagnostic.path,
        diagnostic.rule,
        diagnostic.message,
        diagnostic.owner_or_waiver_hint,
        diagnostic.next_action
    )
}

fn read_to_string(root: &Path, relative: &str) -> Result<String, String> {
    let path = root.join(relative);
    fs::read_to_string(&path).map_err(|error| format!("failed to read {}: {error}", path.display()))
}

fn load_repository_model(root: &Path, rules: &LayoutRules) -> Result<RepositoryModel, String> {
    let docs = LayoutDocs {
        agents: read_to_string(root, AGENTS_PATH)?,
        readme: read_to_string(root, README_PATH)?,
        architecture: read_to_string(root, ARCHITECTURE_PATH)?,
        checklist: read_to_string(root, CHECKLIST_PATH)?,
    };
    let mut tree = Vec::new();
    collect_tree_entries(root, root, &mut tree)?;
    tree.sort_by(|left, right| left.path.cmp(&right.path));

    let mut generated_text = BTreeMap::new();
    for surface in &rules.generated_surfaces {
        if tree_contains_path(&tree, surface.path) {
            generated_text.insert(
                surface.path.to_string(),
                read_to_string(root, surface.path)?,
            );
        }
    }

    Ok(RepositoryModel {
        docs,
        tree,
        generated_text,
    })
}

fn collect_tree_entries(
    root: &Path,
    current: &Path,
    tree: &mut Vec<TreeEntry>,
) -> Result<(), String> {
    let entries = fs::read_dir(current)
        .map_err(|error| format!("failed to read directory {}: {error}", current.display()))?;
    for entry_result in entries {
        let entry = entry_result.map_err(|error| {
            format!(
                "failed to read directory entry {}: {error}",
                current.display()
            )
        })?;
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)
            .map_err(|error| format!("failed to inspect {}: {error}", path.display()))?;
        let relative = relative_path(root, &path)?;
        let kind = if metadata.file_type().is_symlink() {
            EntryKind::Symlink
        } else if metadata.is_dir() {
            EntryKind::Directory
        } else {
            EntryKind::File
        };
        tree.push(TreeEntry {
            path: relative.clone(),
            kind,
        });

        if metadata.is_dir() && !should_skip_walk(&relative) {
            collect_tree_entries(root, &path, tree)?;
        }
    }
    Ok(())
}

fn should_skip_walk(relative: &str) -> bool {
    if is_git_boundary(relative)
        || relative == TARGET_DIR_NAME
        || relative == RESULT_LINK_NAME
        || relative.starts_with(RESULT_LINK_PREFIX)
    {
        return true;
    }
    IGNORED_WALK_DIRS.iter().any(|ignored| {
        relative == *ignored || relative.starts_with(&format!("{ignored}{PATH_SEPARATOR}"))
    })
}

fn relative_path(root: &Path, path: &Path) -> Result<String, String> {
    path.strip_prefix(root)
        .map_err(|error| format!("failed to relativize {}: {error}", path.display()))?
        .to_str()
        .map(|text| text.replace('\\', "/"))
        .ok_or_else(|| format!("{} is not valid UTF-8", path.display()))
}

fn fixture_contract_text() -> String {
    REQUIRED_CONTRACT_PHRASES.join("\n")
}

fn fixture_registry_table() -> String {
    format!(
        "{contract}\n\n| Path | Role | Ownership | Local notes | Default gates |\n| --- | --- | --- | --- | --- |\n| `{stevenarella}` | Core client | Parent repository owned | `{stevenarella_agents}` | Included |\n| `{valence}` | Core server | Parent repository owned | `{valence_agents}` | Included |\n| `{compat}` | Harness | Parent repository owned | `{agents}` plus `{architecture}` | Included |\n| `docs/` | Documentation | Parent repository owned | `{architecture}` | Included |\n| `{hyperion}` | independent engine | Nested repo, separate jj/git workflow | `hyperion/AGENTS.md` and `hyperion/.agent/napkin.md` | Excluded unless explicitly selected |\n| `{leafish}` | Reference client checkout | reference-only nested Git checkout | {leafish_waiver} | Excluded from default gates unless explicitly selected |\n",
        contract = fixture_contract_text(),
        stevenarella = STEVENARELLA_LABEL,
        stevenarella_agents = STEVENARELLA_AGENTS_PATH,
        valence = VALENCE_LABEL,
        valence_agents = VALENCE_AGENTS_PATH,
        compat = "compat/",
        agents = AGENTS_PATH,
        architecture = ARCHITECTURE_PATH,
        hyperion = HYPERION_LABEL,
        leafish = LEAFISH_LABEL,
        leafish_waiver = LEAFISH_WAIVER_TEXT,
    )
}

fn fixture_valid_model() -> RepositoryModel {
    let docs = LayoutDocs {
        agents: format!(
            "{STEVENARELLA_AGENTS_PATH} {VALENCE_AGENTS_PATH} {CHECKLIST_PATH} {LEAFISH_LABEL} is {REFERENCE_ONLY_TEXT} {NESTED_GIT_TEXT}; do not use {PARENT_STATUS_TEXT}."
        ),
        readme: format!(
            "{STEVENARELLA_AGENTS_PATH} {VALENCE_AGENTS_PATH} {CHECKLIST_PATH} {LEAFISH_LABEL} is {REFERENCE_ONLY_TEXT}, {DEFAULT_GATE_EXCLUSION_TEXT}, and uses {OPT_IN_TEXT} commands."
        ),
        architecture: format!(
            "{STEVENARELLA_AGENTS_PATH} {VALENCE_AGENTS_PATH} {CHECKLIST_PATH} {LEAFISH_LABEL} is {REFERENCE_ONLY_TEXT} {NESTED_GIT_TEXT}; see {CHECKLIST_PATH}."
        ),
        checklist: fixture_registry_table(),
    };
    let tree = vec![
        tree_dir("clients"),
        tree_dir("clients/stevenarella"),
        tree_file(STEVENARELLA_AGENTS_PATH),
        tree_dir("servers"),
        tree_dir("servers/valence"),
        tree_file(VALENCE_AGENTS_PATH),
        tree_dir("compat"),
        tree_file(AGENTS_PATH),
        tree_file(README_PATH),
        tree_dir("docs"),
        tree_file(ARCHITECTURE_PATH),
        tree_file(CHECKLIST_PATH),
        tree_dir("hyperion"),
        tree_dir(HYPERION_GIT_PATH),
        tree_file("hyperion/AGENTS.md"),
        tree_file("hyperion/.agent/napkin.md"),
        tree_dir("Leafish"),
        tree_dir(LEAFISH_GIT_PATH),
        tree_file(GENERATED_RUST_PATH),
        tree_file(GENERATED_INDEX_PATH),
    ];
    let generated_text = BTreeMap::from([
        (
            GENERATED_RUST_PATH.to_string(),
            GENERATED_RUST_MARKER.to_string(),
        ),
        (
            GENERATED_INDEX_PATH.to_string(),
            GENERATED_INDEX_MARKER.to_string(),
        ),
    ]);

    RepositoryModel {
        docs,
        tree,
        generated_text,
    }
}

fn tree_dir(path: &str) -> TreeEntry {
    TreeEntry {
        path: path.to_string(),
        kind: EntryKind::Directory,
    }
}

fn tree_file(path: &str) -> TreeEntry {
    TreeEntry {
        path: path.to_string(),
        kind: EntryKind::File,
    }
}

fn assert_report_has_code(report: &GuardReport, code: &str) -> Result<(), String> {
    if report
        .diagnostics
        .iter()
        .any(|diagnostic| diagnostic.code == code)
    {
        Ok(())
    } else {
        Err(format!(
            "expected diagnostic code {code}; got {:?}",
            report.diagnostics
        ))
    }
}

fn run_self_test() -> Result<(), String> {
    let rules = default_rules();
    let valid = fixture_valid_model();
    let valid_report = validate_layout(&valid, &rules);
    if !valid_report.diagnostics.is_empty() {
        return Err(format!(
            "positive fixture unexpectedly failed: {:?}",
            valid_report.diagnostics
        ));
    }

    let mut undocumented_root = valid.clone();
    undocumented_root.tree.push(tree_dir("scratch-component"));
    let undocumented_root_report = validate_layout(&undocumented_root, &rules);
    assert_report_has_code(&undocumented_root_report, "undocumented_root_directory")?;
    if !report_has_required_findings(&undocumented_root_report) {
        return Err(String::from("undocumented root fixture should be required"));
    }

    let mut surprise_git = valid.clone();
    surprise_git.tree.push(tree_dir("vendor"));
    surprise_git.tree.push(tree_dir("vendor/.git"));
    let surprise_git_report = validate_layout(&surprise_git, &rules);
    assert_report_has_code(&surprise_git_report, "undocumented_nested_git")?;

    let mut transient_root = valid.clone();
    transient_root.tree.push(TreeEntry {
        path: String::from("target-mc-compat-live.log"),
        kind: EntryKind::File,
    });
    let transient_report = validate_layout(&transient_root, &rules);
    assert_report_has_code(&transient_report, "root_transient_artifact")?;
    if report_has_required_findings(&transient_report) {
        return Err(String::from("transient root artifact should be advisory"));
    }

    let mut missing_docs = valid.clone();
    missing_docs
        .tree
        .retain(|entry| entry.path != STEVENARELLA_AGENTS_PATH);
    let missing_docs_report = validate_layout(&missing_docs, &rules);
    assert_report_has_code(&missing_docs_report, "missing_subtree_documentation")?;

    let mut generated_drift = valid.clone();
    generated_drift.generated_text.insert(
        GENERATED_RUST_PATH.to_string(),
        String::from("// hand edited generated table"),
    );
    let generated_drift_report = validate_layout(&generated_drift, &rules);
    assert_report_has_code(&generated_drift_report, "generated_marker_drift")?;

    let mut registry_mismatch = valid.clone();
    registry_mismatch
        .tree
        .push(tree_dir("clients/stevenarella/.git"));
    let registry_mismatch_report = validate_layout(&registry_mismatch, &rules);
    assert_report_has_code(&registry_mismatch_report, "component_registry_mismatch")?;

    let mut missing_contract = valid;
    missing_contract.docs.checklist = String::from("| Path | Role | Ownership | Local notes | Default gates |\n| --- | --- | --- | --- | --- |\n");
    let missing_contract_report = validate_layout(&missing_contract, &rules);
    assert_report_has_code(&missing_contract_report, "missing_layout_guard_contract")?;

    Ok(())
}

#[derive(Debug, Clone)]
struct Command {
    root: PathBuf,
    self_test: bool,
}

fn parse_args() -> Result<Command, String> {
    let mut args = env::args().skip(1);
    let mut root = PathBuf::from(DEFAULT_ROOT);
    let mut self_test = false;

    while let Some(arg) = args.next() {
        if arg == ROOT_FLAG {
            let value = args
                .next()
                .ok_or_else(|| format!("{ROOT_FLAG} requires a path"))?;
            root = PathBuf::from(value);
        } else if arg == SELF_TEST_FLAG {
            self_test = true;
        } else {
            return Err(format!("unknown argument: {arg}"));
        }
    }

    Ok(Command { root, self_test })
}

fn run(command: Command) -> Result<String, String> {
    if command.self_test {
        run_self_test()?;
        return Ok(String::from(SELF_TEST_SUCCESS_MESSAGE));
    }

    let rules = default_rules();
    let model = load_repository_model(&command.root, &rules)?;
    let report = validate_layout(&model, &rules);
    if report_has_required_findings(&report) {
        Err(render_diagnostics(&report))
    } else {
        Ok(render_success(&report))
    }
}

fn main() -> ExitCode {
    let command = match parse_args() {
        Ok(command) => command,
        Err(error) => {
            eprintln!("{error}");
            return FAILURE;
        }
    };

    match run(command) {
        Ok(message) => {
            println!("{message}");
            SUCCESS
        }
        Err(error) => {
            eprintln!("{error}");
            FAILURE
        }
    }
}
