use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::Path;
use std::process::ExitCode;

const CONTRACT_PATH: &str = "compat/config/scenario-contracts.ncl";
const SCENARIO_MANIFEST_PATH: &str = "compat/config/scenario-manifest.ncl";
const RUNNER_LIBRARY_PATH: &str = "compat/runner/src/lib.rs";
const RUNNER_RECEIPT_VALIDATION_PATH: &str = "compat/runner/src/receipt_validation.rs";
const STEVENARELLA_SERVER_PATH: &str = "clients/stevenarella/src/server/mod.rs";
const VALENCE_CTF_PATH: &str = "servers/valence/examples/ctf.rs";
const VALENCE_SURVIVAL_PATH: &str = "servers/valence/examples/survival_compat.rs";
const RUNNER_GENERATED_PATH: &str = "compat/runner/src/scenario_contracts_generated.rs";
const STEVENARELLA_GENERATED_PATH: &str =
    "clients/stevenarella/src/server/scenario_contracts_generated.rs";
const VALENCE_GENERATED_PATH: &str = "servers/valence/examples/scenario_contracts_generated.rs";
const GENERATED_INVENTORY_PATH: &str = "docs/evidence/scenario-contract-inventory.generated.md";
const SUPPORTED_CONTRACT_SCHEMA: &str = "mc.compat.scenario-contracts.v1";
const SUPPORTED_MANIFEST_SCHEMA: &str = "mc.compat.scenario-manifest.v1";
const CONTRACT_ROW_START: &str = "{ id = ";
const FIELD_STRING_SEPARATOR: &str = " = \"";
const ARRAY_START: &str = "[";
const ARRAY_END: &str = "]";
const STRING_QUOTE: char = '"';
const STRING_ARRAY_SEPARATOR: &str = ",";
const MC_COMPAT_TOKEN_PREFIX: &str = "MC_COMPAT_";
const RECEIPT_TOKEN_PREFIX: &str = "mc.compat.";
const RECEIPT_QUOTED_PREFIX: &str = "\"mc.compat.";
const SELF_TEST_FLAG: &str = "--self-test";
const CHECK_GENERATED_SURFACES_FLAG: &str = "--check-generated-surfaces";
const WRITE_GENERATED_SURFACES_FLAG: &str = "--write-generated-surfaces";
const EXIT_SUCCESS: ExitCode = ExitCode::SUCCESS;
const EXIT_FAILURE: ExitCode = ExitCode::FAILURE;
const MIN_CONTRACT_VALUE_COUNT: usize = 1;
const MIN_SCENARIO_ROW_COUNT: usize = 1;
const RUSTFMT_DEFAULT_MAX_WIDTH: usize = 100;
const GENERATED_HEADER: &str =
    "// @generated by tools/check_scenario_contracts.rs --write-generated-surfaces";
const GENERATED_DOC_MARKER: &str =
    "<!-- @generated by tools/check_scenario_contracts.rs --write-generated-surfaces; edit compat/config/scenario-contracts.ncl and compat/config/scenario-manifest.ncl instead. -->";
const NON_CLAIM_BOUNDARIES: &[&str] = &[
    "broad Minecraft compatibility",
    "semantic equivalence",
    "production readiness",
    "public-server safety",
    "full CTF correctness",
    "full survival correctness",
];
const SUPPORTED_KINDS: &[&str] = &[
    "probe_env",
    "fixture_toggle",
    "fixture_state",
    "runtime_env",
    "receipt_identifier",
];
const ENV_KINDS: &[&str] = &[
    "probe_env",
    "fixture_toggle",
    "fixture_state",
    "runtime_env",
];
const SUPPORTED_STATUS: &[&str] = &["canonical", "compatibility_alias", "retired_alias"];
const CONSUMER_PATHS: &[&str] = &[
    RUNNER_LIBRARY_PATH,
    RUNNER_RECEIPT_VALIDATION_PATH,
    STEVENARELLA_SERVER_PATH,
    VALENCE_CTF_PATH,
    VALENCE_SURVIVAL_PATH,
];
const GENERATED_SURFACE_PATHS: &[&str] = &[
    RUNNER_GENERATED_PATH,
    STEVENARELLA_GENERATED_PATH,
    VALENCE_GENERATED_PATH,
    GENERATED_INVENTORY_PATH,
];

#[derive(Debug, Clone, PartialEq, Eq)]
struct Contract {
    schema: String,
    scenario_manifest: String,
    non_claim_boundaries: Vec<String>,
    values: Vec<ContractValue>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ContractValue {
    id: String,
    kind: String,
    value: String,
    status: String,
    fixture_owner: String,
    migration_action: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ScenarioManifest {
    schema: String,
    rows: Vec<ScenarioRow>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ScenarioRow {
    name: String,
    aliases: Vec<String>,
    client_milestones: Vec<String>,
    server_milestones: Vec<String>,
    forbidden_patterns: Vec<String>,
    receipt_expectations: Vec<String>,
    migration_state: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ConsumerScan {
    env_by_path: BTreeMap<String, Vec<String>>,
    receipts_by_path: BTreeMap<String, Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct GeneratedSurface {
    path: &'static str,
    content: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct RepoInputs {
    contract_text: String,
    manifest_text: String,
    consumers: BTreeMap<String, String>,
    generated_surfaces: BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ValidationReport {
    contract_value_count: usize,
    scenario_count: usize,
    raw_env_count: usize,
    raw_receipt_count: usize,
}

fn main() -> ExitCode {
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|arg| arg == SELF_TEST_FLAG) {
        return match run_self_tests() {
            Ok(summary) => {
                println!("scenario contract self-test passed: {summary}");
                EXIT_SUCCESS
            }
            Err(errors) => {
                print_errors(&errors);
                EXIT_FAILURE
            }
        };
    }

    if args.iter().any(|arg| arg == WRITE_GENERATED_SURFACES_FLAG) {
        return match run_write_generated_surfaces(Path::new(".")) {
            Ok(summary) => {
                println!("scenario contract generated surfaces refreshed: {summary}");
                EXIT_SUCCESS
            }
            Err(errors) => {
                print_errors(&errors);
                EXIT_FAILURE
            }
        };
    }

    let result = run_repo_check(Path::new("."), true);
    match result {
        Ok(report) => {
            let mode = if args.iter().any(|arg| arg == CHECK_GENERATED_SURFACES_FLAG) {
                "generated-surface"
            } else {
                "contract"
            };
            println!(
                "scenario {mode} check passed: values={} scenarios={} env_tokens={} receipt_tokens={}",
                report.contract_value_count,
                report.scenario_count,
                report.raw_env_count,
                report.raw_receipt_count
            );
            EXIT_SUCCESS
        }
        Err(errors) => {
            print_errors(&errors);
            EXIT_FAILURE
        }
    }
}

fn print_errors(errors: &[String]) {
    for error in errors {
        eprintln!("scenario contract check failed: {error}");
    }
}

fn run_repo_check(root: &Path, check_generated: bool) -> Result<ValidationReport, Vec<String>> {
    let inputs = read_repo_inputs(root)?;
    validate_repo_inputs(&inputs, check_generated)
}

fn read_repo_inputs(root: &Path) -> Result<RepoInputs, Vec<String>> {
    let contract_text = read_repo_file(root, CONTRACT_PATH)?;
    let manifest_text = read_repo_file(root, SCENARIO_MANIFEST_PATH)?;
    let mut consumers = BTreeMap::new();
    for path in CONSUMER_PATHS {
        consumers.insert((*path).to_string(), read_repo_file(root, path)?);
    }
    let mut generated_surfaces = BTreeMap::new();
    for path in GENERATED_SURFACE_PATHS {
        generated_surfaces.insert((*path).to_string(), read_repo_file(root, path)?);
    }
    Ok(RepoInputs {
        contract_text,
        manifest_text,
        consumers,
        generated_surfaces,
    })
}

fn read_repo_file(root: &Path, path: &str) -> Result<String, Vec<String>> {
    fs::read_to_string(root.join(path)).map_err(|err| vec![format!("{path}: {err}")])
}

fn run_write_generated_surfaces(root: &Path) -> Result<String, Vec<String>> {
    let contract_text = read_repo_file(root, CONTRACT_PATH)?;
    let manifest_text = read_repo_file(root, SCENARIO_MANIFEST_PATH)?;
    let contract = parse_contract(&contract_text)?;
    let manifest = parse_scenario_manifest(&manifest_text)?;
    let mut consumers = BTreeMap::new();
    for path in CONSUMER_PATHS {
        consumers.insert((*path).to_string(), read_repo_file(root, path)?);
    }
    let scan = scan_consumers(&consumers);
    let surfaces = render_generated_surfaces(&contract, &manifest, &scan)?;
    validate_generated_output_paths(&surfaces)?;

    let mut errors = Vec::new();
    for surface in &surfaces {
        let path = root.join(surface.path);
        if let Some(parent) = path.parent() {
            if let Err(err) = fs::create_dir_all(parent) {
                errors.push(format!("create {}: {err}", parent.display()));
                continue;
            }
        }
        if let Err(err) = fs::write(&path, &surface.content) {
            errors.push(format!("write {}: {err}", path.display()));
        }
    }
    if errors.is_empty() {
        Ok(format!("{} surfaces", surfaces.len()))
    } else {
        Err(errors)
    }
}

fn validate_repo_inputs(
    inputs: &RepoInputs,
    check_generated: bool,
) -> Result<ValidationReport, Vec<String>> {
    let mut errors = Vec::new();
    let contract = collect_result(&mut errors, parse_contract(&inputs.contract_text));
    let manifest = collect_result(&mut errors, parse_scenario_manifest(&inputs.manifest_text));
    if !errors.is_empty() {
        return Err(errors);
    }
    let contract = contract.expect("contract parsed when errors are empty");
    let manifest = manifest.expect("manifest parsed when errors are empty");
    let scan = scan_consumers(&inputs.consumers);

    errors.extend(validate_contract(&contract));
    errors.extend(validate_manifest(&manifest, &contract));
    errors.extend(validate_consumer_scan(&contract, &scan));

    if check_generated {
        match render_generated_surfaces(&contract, &manifest, &scan) {
            Ok(surfaces) => {
                errors.extend(
                    validate_generated_output_paths(&surfaces)
                        .err()
                        .unwrap_or_default(),
                );
                errors.extend(compare_generated_surfaces(
                    &surfaces,
                    &inputs.generated_surfaces,
                ));
            }
            Err(mut render_errors) => errors.append(&mut render_errors),
        }
    }

    if errors.is_empty() {
        Ok(ValidationReport {
            contract_value_count: contract.values.len(),
            scenario_count: manifest.rows.len(),
            raw_env_count: scan.env_token_count(),
            raw_receipt_count: scan.receipt_token_count(),
        })
    } else {
        Err(errors)
    }
}

fn collect_result<T>(errors: &mut Vec<String>, result: Result<T, Vec<String>>) -> Option<T> {
    match result {
        Ok(value) => Some(value),
        Err(mut next_errors) => {
            errors.append(&mut next_errors);
            None
        }
    }
}

impl ConsumerScan {
    fn env_token_count(&self) -> usize {
        self.env_by_path.values().map(Vec::len).sum()
    }

    fn receipt_token_count(&self) -> usize {
        self.receipts_by_path.values().map(Vec::len).sum()
    }
}

fn parse_contract(text: &str) -> Result<Contract, Vec<String>> {
    let schema = parse_top_level_string(text, "schema")?;
    let scenario_manifest = parse_top_level_string(text, "scenario_manifest")?;
    let non_claim_boundaries = parse_top_level_string_array(text, "non_claim_boundaries")?;
    let values = parse_contract_values(text)?;
    Ok(Contract {
        schema,
        scenario_manifest,
        non_claim_boundaries,
        values,
    })
}

fn parse_scenario_manifest(text: &str) -> Result<ScenarioManifest, Vec<String>> {
    let schema = parse_top_level_string(text, "schema")?;
    let rows = parse_scenario_rows(text)?;
    Ok(ScenarioManifest { schema, rows })
}

fn parse_top_level_string(text: &str, field: &str) -> Result<String, Vec<String>> {
    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.starts_with(&format!("{field}{FIELD_STRING_SEPARATOR}")) {
            return parse_string_value(line, field).map_err(|err| vec![err]);
        }
    }
    Err(vec![format!("missing top-level string field {field}")])
}

fn parse_top_level_string_array(text: &str, field: &str) -> Result<Vec<String>, Vec<String>> {
    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.starts_with(&format!("{field} = ")) {
            return parse_string_array(line, field).map_err(|err| vec![err]);
        }
    }
    Err(vec![format!("missing top-level array field {field}")])
}

fn parse_contract_values(text: &str) -> Result<Vec<ContractValue>, Vec<String>> {
    let mut values = Vec::new();
    let mut errors = Vec::new();
    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.starts_with(CONTRACT_ROW_START) {
            match parse_contract_value(line) {
                Ok(value) => values.push(value),
                Err(mut row_errors) => errors.append(&mut row_errors),
            }
        }
    }
    if values.is_empty() {
        errors.push("contract contains no values rows".to_string());
    }
    if errors.is_empty() {
        Ok(values)
    } else {
        Err(errors)
    }
}

fn parse_contract_value(line: &str) -> Result<ContractValue, Vec<String>> {
    let mut errors = Vec::new();
    let id = parse_inline_string_field(line, "id").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let kind = parse_inline_string_field(line, "kind").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let value = parse_inline_string_field(line, "value").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let status = parse_inline_string_field(line, "status").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let fixture_owner = parse_inline_string_field(line, "fixture_owner").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let migration_action =
        parse_inline_string_field(line, "migration_action").unwrap_or_else(|err| {
            errors.push(err);
            String::new()
        });

    if errors.is_empty() {
        Ok(ContractValue {
            id,
            kind,
            value,
            status,
            fixture_owner,
            migration_action,
        })
    } else {
        Err(errors)
    }
}

fn parse_scenario_rows(text: &str) -> Result<Vec<ScenarioRow>, Vec<String>> {
    let mut rows = Vec::new();
    let mut errors = Vec::new();
    let mut in_scenarios = false;
    let mut current = Vec::new();

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line == "scenarios = [" {
            in_scenarios = true;
            continue;
        }
        if in_scenarios && line == "]," {
            if !current.is_empty() {
                errors.push("unterminated scenario row before scenarios end".to_string());
            }
            break;
        }
        if !in_scenarios {
            continue;
        }
        if line == "{" {
            current.clear();
            continue;
        }
        if line == "}," {
            match parse_scenario_row(&current) {
                Ok(row) => rows.push(row),
                Err(mut row_errors) => errors.append(&mut row_errors),
            }
            current.clear();
            continue;
        }
        if !current.is_empty() || line.starts_with("name = ") {
            current.push(line.to_string());
        }
    }

    if rows.is_empty() {
        errors.push("scenario manifest contains no scenario rows".to_string());
    }
    if errors.is_empty() {
        Ok(rows)
    } else {
        Err(errors)
    }
}

fn parse_scenario_row(lines: &[String]) -> Result<ScenarioRow, Vec<String>> {
    let mut errors = Vec::new();
    let name = parse_named_line_string(lines, "name").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });
    let aliases = parse_named_line_array(lines, "aliases").unwrap_or_else(|err| {
        errors.push(err);
        Vec::new()
    });
    let client_milestones =
        parse_named_line_array(lines, "client_milestones").unwrap_or_else(|err| {
            errors.push(err);
            Vec::new()
        });
    let server_milestones =
        parse_named_line_array(lines, "server_milestones").unwrap_or_else(|err| {
            errors.push(err);
            Vec::new()
        });
    let forbidden_patterns =
        parse_named_line_array(lines, "forbidden_patterns").unwrap_or_else(|err| {
            errors.push(err);
            Vec::new()
        });
    let receipt_expectations = parse_named_line_array(lines, "receipt_expectations")
        .unwrap_or_else(|err| {
            errors.push(err);
            Vec::new()
        });
    let migration_state = parse_named_line_string(lines, "migration_state").unwrap_or_else(|err| {
        errors.push(err);
        String::new()
    });

    if errors.is_empty() {
        Ok(ScenarioRow {
            name,
            aliases,
            client_milestones,
            server_milestones,
            forbidden_patterns,
            receipt_expectations,
            migration_state,
        })
    } else {
        Err(errors)
    }
}

fn parse_named_line_string(lines: &[String], field: &str) -> Result<String, String> {
    for line in lines {
        if line.starts_with(&format!("{field}{FIELD_STRING_SEPARATOR}")) {
            return parse_string_value(line, field);
        }
    }
    Err(format!("scenario row missing string field {field}"))
}

fn parse_named_line_array(lines: &[String], field: &str) -> Result<Vec<String>, String> {
    for line in lines {
        if line.starts_with(&format!("{field} = ")) {
            return parse_string_array(line, field);
        }
    }
    Err(format!("scenario row missing array field {field}"))
}

fn parse_string_value(line: &str, field: &str) -> Result<String, String> {
    let prefix = format!("{field}{FIELD_STRING_SEPARATOR}");
    let rest = line
        .strip_prefix(&prefix)
        .ok_or_else(|| format!("{field}: missing string prefix"))?;
    let end = rest
        .find(STRING_QUOTE)
        .ok_or_else(|| format!("{field}: missing closing quote"))?;
    Ok(rest[..end].to_string())
}

fn parse_inline_string_field(line: &str, field: &str) -> Result<String, String> {
    let needle = format!("{field}{FIELD_STRING_SEPARATOR}");
    let start = line
        .find(&needle)
        .ok_or_else(|| format!("contract row missing string field {field}"))?;
    let rest = &line[start + needle.len()..];
    let end = rest
        .find(STRING_QUOTE)
        .ok_or_else(|| format!("contract row field {field} missing closing quote"))?;
    Ok(rest[..end].to_string())
}

fn parse_string_array(line: &str, field: &str) -> Result<Vec<String>, String> {
    let prefix = format!("{field} = ");
    let rest = line
        .strip_prefix(&prefix)
        .ok_or_else(|| format!("{field}: missing array prefix"))?;
    let start = rest
        .find(ARRAY_START)
        .ok_or_else(|| format!("{field}: missing array start"))?;
    let end = rest
        .rfind(ARRAY_END)
        .ok_or_else(|| format!("{field}: missing array end"))?;
    if end <= start {
        return Err(format!("{field}: malformed array bounds"));
    }
    let inside = &rest[start + ARRAY_START.len()..end];
    if inside.trim().is_empty() {
        return Ok(Vec::new());
    }
    inside
        .split(STRING_ARRAY_SEPARATOR)
        .map(parse_array_item)
        .collect::<Result<Vec<_>, _>>()
}

fn parse_array_item(raw: &str) -> Result<String, String> {
    let item = raw.trim();
    if !(item.starts_with(STRING_QUOTE) && item.ends_with(STRING_QUOTE)) {
        return Err(format!("array item is not quoted: {item}"));
    }
    Ok(item[1..item.len() - 1].to_string())
}

fn scan_consumers(consumers: &BTreeMap<String, String>) -> ConsumerScan {
    let mut env_by_path = BTreeMap::new();
    let mut receipts_by_path = BTreeMap::new();
    for (path, text) in consumers {
        env_by_path.insert(
            path.clone(),
            unique_sorted(extract_prefixed_tokens(text, MC_COMPAT_TOKEN_PREFIX)),
        );
        receipts_by_path.insert(
            path.clone(),
            unique_sorted(extract_quoted_tokens(text, RECEIPT_QUOTED_PREFIX)),
        );
    }
    ConsumerScan {
        env_by_path,
        receipts_by_path,
    }
}

fn extract_prefixed_tokens(text: &str, token_prefix: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut search_start = 0;
    while let Some(relative_start) = text[search_start..].find(token_prefix) {
        let absolute_start = search_start + relative_start;
        let rest = &text[absolute_start..];
        let end = rest
            .char_indices()
            .find_map(|(index, ch)| {
                if ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_' {
                    None
                } else {
                    Some(index)
                }
            })
            .unwrap_or(rest.len());
        tokens.push(rest[..end].trim_end_matches('\\').to_string());
        search_start = absolute_start + end;
    }
    tokens
}

fn extract_quoted_tokens(text: &str, quoted_prefix: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut search_start = 0;
    while let Some(relative_start) = text[search_start..].find(quoted_prefix) {
        let absolute_start = search_start + relative_start + 1;
        let rest = &text[absolute_start..];
        if let Some(relative_end) = rest.find(STRING_QUOTE) {
            tokens.push(rest[..relative_end].trim_end_matches('\\').to_string());
            search_start = absolute_start + relative_end + 1;
        } else {
            break;
        }
    }
    tokens
}

fn unique_sorted(values: Vec<String>) -> Vec<String> {
    values
        .into_iter()
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn validate_contract(contract: &Contract) -> Vec<String> {
    let mut errors = Vec::new();
    if contract.schema != SUPPORTED_CONTRACT_SCHEMA {
        errors.push(format!(
            "unsupported scenario contract schema {}",
            contract.schema
        ));
    }
    if contract.scenario_manifest != SCENARIO_MANIFEST_PATH {
        errors.push(format!(
            "scenario_manifest must point at {SCENARIO_MANIFEST_PATH}, got {}",
            contract.scenario_manifest
        ));
    }
    if contract.values.len() < MIN_CONTRACT_VALUE_COUNT {
        errors.push("scenario contract has no values".to_string());
    }
    for required in NON_CLAIM_BOUNDARIES {
        if !contract
            .non_claim_boundaries
            .iter()
            .any(|boundary| boundary == required)
        {
            errors.push(format!("missing non-claim boundary {required}"));
        }
    }

    let mut ids = BTreeSet::new();
    let mut values = BTreeSet::new();
    for value in &contract.values {
        validate_contract_value(value, &mut errors);
        if !ids.insert(value.id.clone()) {
            errors.push(format!("duplicate contract id {}", value.id));
        }
        if !values.insert(value.value.clone()) {
            errors.push(format!("duplicate contract value {}", value.value));
        }
    }
    errors
}

fn validate_contract_value(value: &ContractValue, errors: &mut Vec<String>) {
    if value.id.trim().is_empty() {
        errors.push(format!("{} has empty id", value.value));
    }
    if value.value.trim().is_empty() {
        errors.push(format!("{} has empty value", value.id));
    }
    if !SUPPORTED_KINDS.contains(&value.kind.as_str()) {
        errors.push(format!("{} has unsupported kind {}", value.id, value.kind));
    }
    if !SUPPORTED_STATUS.contains(&value.status.as_str()) {
        errors.push(format!(
            "{} has unsupported status {}",
            value.id, value.status
        ));
    }
    if value.fixture_owner.trim().is_empty() {
        errors.push(format!("{} has empty fixture_owner", value.id));
    }
    if value.migration_action.trim().is_empty() {
        errors.push(format!("{} has empty migration_action", value.id));
    }
    if ENV_KINDS.contains(&value.kind.as_str()) && !value.value.starts_with(MC_COMPAT_TOKEN_PREFIX)
    {
        errors.push(format!(
            "{} env-like value must start with {MC_COMPAT_TOKEN_PREFIX}",
            value.id
        ));
    }
    if value.kind == "receipt_identifier" && !value.value.starts_with(RECEIPT_TOKEN_PREFIX) {
        errors.push(format!(
            "{} receipt identifier must start with {RECEIPT_TOKEN_PREFIX}",
            value.id
        ));
    }
}

fn validate_manifest(manifest: &ScenarioManifest, contract: &Contract) -> Vec<String> {
    let mut errors = Vec::new();
    if manifest.schema != SUPPORTED_MANIFEST_SCHEMA {
        errors.push(format!(
            "unsupported scenario manifest schema {}",
            manifest.schema
        ));
    }
    if manifest.rows.len() < MIN_SCENARIO_ROW_COUNT {
        errors.push("scenario manifest has no rows".to_string());
    }

    let mut names = BTreeSet::new();
    let mut aliases = BTreeSet::new();
    for row in &manifest.rows {
        if row.name.is_empty() {
            errors.push("scenario row has empty name".to_string());
        }
        if !names.insert(row.name.clone()) {
            errors.push(format!("duplicate scenario name {}", row.name));
        }
        if !row.aliases.iter().any(|alias| alias == &row.name) {
            errors.push(format!("scenario {} aliases omit canonical name", row.name));
        }
        for alias in &row.aliases {
            if !aliases.insert(alias.clone()) {
                errors.push(format!("duplicate scenario alias {alias}"));
            }
        }
        if row.client_milestones.is_empty() {
            errors.push(format!("scenario {} has no client milestones", row.name));
        }
        if row.forbidden_patterns.is_empty() {
            errors.push(format!("scenario {} has no forbidden patterns", row.name));
        }
    }

    let receipt_expectations = manifest
        .rows
        .iter()
        .flat_map(|row| row.receipt_expectations.iter())
        .collect::<BTreeSet<_>>();
    for value in contract
        .values
        .iter()
        .filter(|value| value.kind == "receipt_identifier")
    {
        if value.status == "canonical" && receipt_expectations.is_empty() {
            errors.push(format!(
                "{} cannot be checked because manifest has no receipt expectations",
                value.id
            ));
        }
    }
    errors
}

fn validate_consumer_scan(contract: &Contract, scan: &ConsumerScan) -> Vec<String> {
    let mut errors = Vec::new();
    let env_values = contract
        .values
        .iter()
        .filter(|value| ENV_KINDS.contains(&value.kind.as_str()))
        .map(|value| (value.value.as_str(), value))
        .collect::<BTreeMap<_, _>>();
    let receipt_values = contract
        .values
        .iter()
        .filter(|value| value.kind == "receipt_identifier")
        .map(|value| (value.value.as_str(), value))
        .collect::<BTreeMap<_, _>>();

    for (path, tokens) in &scan.env_by_path {
        for token in tokens {
            match env_values.get(token.as_str()) {
                Some(value) if value.status == "retired_alias" => errors.push(format!(
                    "{path} uses retired alias {} ({})",
                    value.value, value.id
                )),
                Some(_) => {}
                None => errors.push(format!("{path} uses undeclared env var {token}")),
            }
        }
    }

    for (path, tokens) in &scan.receipts_by_path {
        for token in tokens {
            match receipt_values.get(token.as_str()) {
                Some(value) if value.status == "retired_alias" => errors.push(format!(
                    "{path} uses retired receipt alias {} ({})",
                    value.value, value.id
                )),
                Some(_) => {}
                None => errors.push(format!("{path} uses undeclared receipt identifier {token}")),
            }
        }
    }
    errors
}

fn render_generated_surfaces(
    contract: &Contract,
    manifest: &ScenarioManifest,
    scan: &ConsumerScan,
) -> Result<Vec<GeneratedSurface>, Vec<String>> {
    let rust = render_generated_rust(contract)?;
    let inventory = render_generated_inventory(contract, manifest, scan);
    Ok(vec![
        GeneratedSurface {
            path: RUNNER_GENERATED_PATH,
            content: rust.clone(),
        },
        GeneratedSurface {
            path: STEVENARELLA_GENERATED_PATH,
            content: rust.clone(),
        },
        GeneratedSurface {
            path: VALENCE_GENERATED_PATH,
            content: rust,
        },
        GeneratedSurface {
            path: GENERATED_INVENTORY_PATH,
            content: inventory,
        },
    ])
}

fn render_generated_rust(contract: &Contract) -> Result<String, Vec<String>> {
    let mut errors = Vec::new();
    let mut output = String::new();
    output.push_str(GENERATED_HEADER);
    output.push('\n');
    output.push_str("// Do not edit by hand; edit compat/config/scenario-contracts.ncl instead.\n");
    output.push_str("#![allow(dead_code)]\n\n");
    output.push_str(&format!(
        "pub(crate) const SCENARIO_CONTRACT_SCHEMA: &str = {};\n\n",
        rust_string(&contract.schema)
    ));
    for value in contract
        .values
        .iter()
        .filter(|value| ENV_KINDS.contains(&value.kind.as_str()))
    {
        let constant = rust_constant_name(&value.value);
        if constant.is_empty() {
            errors.push(format!("{} cannot render as Rust const", value.value));
            continue;
        }
        output.push_str(&render_rust_const(&constant, &value.value));
    }
    if errors.is_empty() {
        Ok(output)
    } else {
        Err(errors)
    }
}

fn render_rust_const(name: &str, value: &str) -> String {
    let literal = rust_string(value);
    let one_line = format!("pub(crate) const {name}: &str = {literal};\n");
    if one_line.trim_end().len() <= RUSTFMT_DEFAULT_MAX_WIDTH {
        one_line
    } else {
        format!("pub(crate) const {name}: &str =\n    {literal};\n")
    }
}

fn rust_constant_name(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn render_generated_inventory(
    contract: &Contract,
    manifest: &ScenarioManifest,
    scan: &ConsumerScan,
) -> String {
    let mut output = String::new();
    output.push_str("<!-- BEGIN: mc-compat-generated-scenario-contract-inventory -->\n");
    output.push_str(GENERATED_DOC_MARKER);
    output.push_str("\n\n# mc-compat generated scenario contract inventory\n\n");
    output.push_str("This bounded inventory is generated from `compat/config/scenario-contracts.ncl` plus scenario names and milestones from `compat/config/scenario-manifest.ncl`. It records wiring contracts only; it does not claim broad Minecraft compatibility, semantic equivalence, public-server safety, production readiness, full CTF correctness, or full survival correctness.\n\n");
    output.push_str("## Source contracts\n\n");
    output.push_str("| Source | Schema | Role |\n| --- | --- | --- |\n");
    output.push_str(&format!(
        "| `{}` | `{}` | Env vars, fixture toggles, aliases, receipt identifiers, generated Rust constants. |\n",
        CONTRACT_PATH, contract.schema
    ));
    output.push_str(&format!(
        "| `{}` | `{}` | Scenario names, aliases, milestone IDs, forbidden patterns, receipt expectation labels. |\n\n",
        SCENARIO_MANIFEST_PATH, manifest.schema
    ));

    output.push_str("## Scenario env, fixture, and receipt values\n\n");
    output.push_str("| Value | Kind | Status | Fixture owner | Current consumers | Migration action |\n| --- | --- | --- | --- | --- | --- |\n");
    let consumers_by_value = consumers_by_value(scan);
    for value in &contract.values {
        let consumers = consumers_by_value
            .get(&value.value)
            .map(|paths| paths.join("<br>"))
            .unwrap_or_else(|| "(generated-only)".to_string());
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | {} | {} |\n",
            value.value,
            value.kind,
            value.status,
            value.fixture_owner,
            markdown_code_cells(&consumers),
            escape_markdown_cell(&value.migration_action)
        ));
    }

    output.push_str("\n## Scenario names, aliases, and milestone IDs\n\n");
    output.push_str("| Scenario | Aliases | Client milestones | Server milestones | Forbidden patterns | Receipt expectations | Migration state |\n| --- | --- | --- | --- | --- | --- | --- |\n");
    for row in &manifest.rows {
        output.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | `{}` |\n",
            row.name,
            markdown_list(&row.aliases),
            markdown_list(&row.client_milestones),
            markdown_list(&row.server_milestones),
            markdown_list(&row.forbidden_patterns),
            markdown_list(&row.receipt_expectations),
            row.migration_state
        ));
    }
    output.push_str("\n<!-- END: mc-compat-generated-scenario-contract-inventory -->\n");
    output
}

fn consumers_by_value(scan: &ConsumerScan) -> BTreeMap<String, Vec<String>> {
    let mut result: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (path, values) in &scan.env_by_path {
        for value in values {
            result
                .entry(value.clone())
                .or_default()
                .insert(path.clone());
        }
    }
    for (path, values) in &scan.receipts_by_path {
        for value in values {
            result
                .entry(value.clone())
                .or_default()
                .insert(path.clone());
        }
    }
    result
        .into_iter()
        .map(|(value, paths)| (value, paths.into_iter().collect()))
        .collect()
}

fn markdown_list(values: &[String]) -> String {
    if values.is_empty() {
        return String::from("(none)");
    }
    values
        .iter()
        .map(|value| format!("`{}`", escape_markdown_cell(value)))
        .collect::<Vec<_>>()
        .join("<br>")
}

fn markdown_code_cells(value: &str) -> String {
    if value == "(generated-only)" {
        return value.to_string();
    }
    value
        .split("<br>")
        .map(|path| format!("`{}`", escape_markdown_cell(path)))
        .collect::<Vec<_>>()
        .join("<br>")
}

fn escape_markdown_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

fn validate_generated_output_paths(surfaces: &[GeneratedSurface]) -> Result<(), Vec<String>> {
    let mut errors = Vec::new();
    let supported = GENERATED_SURFACE_PATHS
        .iter()
        .copied()
        .collect::<BTreeSet<_>>();
    let mut seen = BTreeSet::new();
    for surface in surfaces {
        if !supported.contains(surface.path) {
            errors.push(format!("unexpected generated path {}", surface.path));
        }
        if surface.path.starts_with('/') || surface.path.contains("..") {
            errors.push(format!("unsafe generated path {}", surface.path));
        }
        if !seen.insert(surface.path) {
            errors.push(format!("duplicate generated path {}", surface.path));
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

fn compare_generated_surfaces(
    expected: &[GeneratedSurface],
    actual_by_path: &BTreeMap<String, String>,
) -> Vec<String> {
    let mut errors = Vec::new();
    for surface in expected {
        match actual_by_path.get(surface.path) {
            Some(actual) if actual == &surface.content => {}
            Some(_) => errors.push(format!(
                "generated surface {} is stale; run tools/check_scenario_contracts.rs --write-generated-surfaces",
                surface.path
            )),
            None => errors.push(format!("generated surface {} was not read", surface.path)),
        }
    }
    errors
}

fn run_self_tests() -> Result<String, Vec<String>> {
    let mut failures = Vec::new();
    expect_ok(
        &mut failures,
        "valid fixture",
        fixture_inputs(false, false, false, false),
    );
    expect_failure_contains(
        &mut failures,
        "missing field fixture",
        fixture_inputs(true, false, false, false),
        "missing string field value",
    );
    expect_failure_contains(
        &mut failures,
        "duplicate value fixture",
        fixture_inputs(false, true, false, false),
        "duplicate contract id",
    );
    expect_failure_contains(
        &mut failures,
        "stale undeclared consumer fixture",
        fixture_inputs(false, false, true, false),
        "undeclared env var",
    );
    expect_failure_contains(
        &mut failures,
        "retired alias fixture",
        fixture_inputs(false, false, false, true),
        "retired alias",
    );
    expect_failure_contains(
        &mut failures,
        "mismatched generated fixture",
        fixture_inputs_with_stale_generated(),
        "generated surface",
    );

    if failures.is_empty() {
        Ok(
            "positive plus missing duplicate stale mismatched and retired-alias fixtures"
                .to_string(),
        )
    } else {
        Err(failures)
    }
}

fn expect_ok(failures: &mut Vec<String>, name: &str, inputs: RepoInputs) {
    if let Err(errors) = validate_repo_inputs(&inputs, true) {
        failures.push(format!("{name}: expected success, got {errors:?}"));
    }
}

fn expect_failure_contains(
    failures: &mut Vec<String>,
    name: &str,
    inputs: RepoInputs,
    expected_fragment: &str,
) {
    match validate_repo_inputs(&inputs, true) {
        Ok(report) => failures.push(format!("{name}: expected failure, got {report:?}")),
        Err(errors) => {
            if !errors.iter().any(|error| error.contains(expected_fragment)) {
                failures.push(format!(
                    "{name}: expected error containing {expected_fragment:?}, got {errors:?}"
                ));
            }
        }
    }
}

fn fixture_inputs(
    missing_field: bool,
    duplicate_row: bool,
    undeclared_consumer: bool,
    retired_alias: bool,
) -> RepoInputs {
    let contract_text = fixture_contract(missing_field, duplicate_row, retired_alias);
    let manifest_text = fixture_manifest();
    let mut consumers = BTreeMap::new();
    let env = if undeclared_consumer {
        "MC_COMPAT_STALE_PROBE"
    } else {
        "MC_COMPAT_ACTIVE_PROBE"
    };
    consumers.insert(
        RUNNER_LIBRARY_PATH.to_string(),
        format!("fn run_main() {{ command.env(\"{env}\", \"1\"); }}"),
    );
    consumers.insert(
        RUNNER_RECEIPT_VALIDATION_PATH.to_string(),
        "const SCHEMA: &str = \"mc.compat.scenario.receipt.v2\";".to_string(),
    );
    consumers.insert(STEVENARELLA_SERVER_PATH.to_string(), String::new());
    consumers.insert(VALENCE_CTF_PATH.to_string(), String::new());
    consumers.insert(VALENCE_SURVIVAL_PATH.to_string(), String::new());

    let generation_contract_text = if missing_field {
        fixture_contract(false, duplicate_row, retired_alias)
    } else {
        contract_text.clone()
    };
    let contract = parse_contract(&generation_contract_text).expect("fixture contract parses");
    let manifest = parse_scenario_manifest(&manifest_text).expect("fixture manifest parses");
    let scan = scan_consumers(&consumers);
    let generated = render_generated_surfaces(&contract, &manifest, &scan)
        .expect("fixture generated surfaces render");
    let generated_surfaces = generated
        .into_iter()
        .map(|surface| (surface.path.to_string(), surface.content))
        .collect();
    RepoInputs {
        contract_text,
        manifest_text,
        consumers,
        generated_surfaces,
    }
}

fn fixture_inputs_with_stale_generated() -> RepoInputs {
    let mut inputs = fixture_inputs(false, false, false, false);
    inputs.generated_surfaces.insert(
        RUNNER_GENERATED_PATH.to_string(),
        "// stale generated output\n".to_string(),
    );
    inputs
}

fn fixture_contract(missing_field: bool, duplicate_row: bool, retired_alias: bool) -> String {
    let status = if retired_alias {
        "retired_alias"
    } else {
        "canonical"
    };
    let first_row = if missing_field {
        "    { id = \"active_probe\", kind = \"probe_env\", status = \"canonical\", fixture_owner = \"runner\", migration_action = \"fixture\" },"
            .to_string()
    } else {
        format!(
            "    {{ id = \"active_probe\", kind = \"probe_env\", value = \"MC_COMPAT_ACTIVE_PROBE\", status = \"{status}\", fixture_owner = \"runner\", migration_action = \"fixture\" }},"
        )
    };
    let duplicate = if duplicate_row {
        "\n    { id = \"active_probe\", kind = \"probe_env\", value = \"MC_COMPAT_ACTIVE_PROBE_DUP\", status = \"canonical\", fixture_owner = \"runner\", migration_action = \"fixture\" },"
    } else {
        ""
    };
    format!(
        "let ContractValue = {{ id | String, kind | String, value | String, status | String, fixture_owner | String, migration_action | String }} in\n{{\n  schema = \"mc.compat.scenario-contracts.v1\",\n  scenario_manifest = \"compat/config/scenario-manifest.ncl\",\n  non_claim_boundaries = [\"broad Minecraft compatibility\", \"semantic equivalence\", \"production readiness\", \"public-server safety\", \"full CTF correctness\", \"full survival correctness\"],\n  values = [\n{first_row}{duplicate}\n    {{ id = \"scenario_receipt_schema\", kind = \"receipt_identifier\", value = \"mc.compat.scenario.receipt.v2\", status = \"canonical\", fixture_owner = \"runner\", migration_action = \"fixture\" }},\n  ],\n}}\n"
    )
}

fn fixture_manifest() -> String {
    "let ScenarioRow = {} in\n{\n  schema = \"mc.compat.scenario-manifest.v1\",\n  scenarios = [\n    {\n      name = \"smoke\",\n      aliases = [\"smoke\"],\n      client_milestones = [\"protocol_detected\"],\n      server_milestones = [],\n      forbidden_patterns = [\"panic\"],\n      receipt_expectations = [\"schema\"],\n      migration_state = \"typed-event-ready\",\n    },\n  ],\n}\n"
        .to_string()
}
