#[cfg(not(target_arch = "wasm32"))]
pub mod capture_startup;
pub mod connection;
pub mod lifecycle;
#[cfg(not(target_arch = "wasm32"))]
pub mod mcp_control;
pub mod startup;
pub mod ticking;
pub mod window_events;
