pub(crate) const ONE_CLIENT: u8 = 1;
pub(crate) const TWO_CLIENTS: u8 = 2;
pub(crate) const ONE_SESSION: u8 = 1;
pub(crate) const TWO_SESSIONS: u8 = 2;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct GeneratedScenarioRow {
    pub(crate) name: &'static str,
    pub(crate) aliases: &'static [&'static str],
    pub(crate) client_milestones: &'static [&'static str],
    pub(crate) server_milestones: &'static [&'static str],
    pub(crate) forbidden_patterns: &'static [&'static str],
    pub(crate) client_count: u8,
    pub(crate) session_count: u8,
    pub(crate) dry_run_check: &'static str,
    pub(crate) dry_run_wrapper: &'static str,
    pub(crate) dry_run_exclusion_reason: &'static str,
    pub(crate) migration_state: &'static str,
}

pub(crate) const DEFAULT_FORBIDDEN_PATTERNS: &[&str] = &[
    "panic",
    "unexpected_eof",
    "protocol_mismatch",
    "decode_error",
];

pub(crate) const FLAG_STATE_FORBIDDEN_PATTERNS: &[&str] = &[
    "panic",
    "unexpected_eof",
    "protocol_mismatch",
    "decode_error",
    "unexpected_flag_capture",
    "unexpected_flag_capture_milestone",
    "unexpected_red_score",
    "unexpected_blue_score",
];

pub(crate) const SCENARIO_MANIFEST_ROWS: &[GeneratedScenarioRow] = &[
    GeneratedScenarioRow {
        name: "smoke",
        aliases: &["smoke"],
        client_milestones: &["protocol_detected"],
        server_milestones: &[],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-dry-run",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "valence-compat-bot-probe",
        aliases: &["valence-compat-bot-probe", "compat-bot-probe"],
        client_milestones: &["protocol_detected", "join_game", "render_tick"],
        server_milestones: &[],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-bot-probe-dry-run",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "flag-score-repeat",
        aliases: &["flag-score-repeat"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "flag_pickup",
            "flag_capture",
            "score_red_1",
            "score_red_2",
        ],
        server_milestones: &["server_username_seen", "server_flag_or_score"],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason:
            "covered by historical live receipt and not yet by a dedicated flake dry-run wrapper",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "blue-flag-score",
        aliases: &["blue-flag-score"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_blue",
            "flag_pickup",
            "flag_capture",
            "score_blue_1",
        ],
        server_milestones: &["server_username_seen", "server_flag_or_score"],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-blue-flag-score-dry-run",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "inventory-interaction",
        aliases: &["inventory-interaction"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "inventory_slot_update",
            "inventory_sword_slot",
            "inventory_wool_slot",
            "inventory_drop_sent",
            "inventory_pickup_seen",
            "inventory_click_sent",
            "inventory_open_container_seen",
            "inventory_container_click_sent",
            "inventory_block_place_sent",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_inventory_hotbar_select",
            "server_inventory_drop",
            "server_inventory_pickup",
            "server_inventory_click",
            "server_inventory_open_container",
            "server_inventory_container_click",
            "server_block_place",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-inventory-interaction-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-inventory-interaction",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "survival-break-place-pickup",
        aliases: &["survival-break-place-pickup"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "survival_break_sent",
            "survival_break_update",
            "survival_pickup_seen",
            "survival_place_sent",
            "survival_place_update",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_survival_join",
            "server_survival_break",
            "server_survival_pickup",
            "server_survival_place",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-survival-break-place-pickup-dry-run",
        dry_run_wrapper: "mc-compat-valence-survival-break-place-pickup",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "survival-chest-persistence",
        aliases: &["survival-chest-persistence"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "survival_chest_open_seen",
            "survival_chest_store_sent",
            "survival_chest_close_sent",
            "survival_chest_reconnect_sent",
            "survival_chest_reopen_seen",
            "survival_chest_persisted_seen",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_survival_chest_open",
            "server_survival_chest_store",
            "server_survival_chest_close",
            "server_survival_chest_reopen",
            "server_survival_chest_persisted",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: TWO_SESSIONS,
        dry_run_check: "",
        dry_run_wrapper: "mc-compat-valence-survival-chest-persistence",
        dry_run_exclusion_reason:
            "active prove-survival-chest-persistence Cairn owns fixture and wrapper promotion",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "survival-crafting-table",
        aliases: &["survival-crafting-table"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "survival_crafting_table_open_seen",
            "survival_crafting_input_a_sent",
            "survival_crafting_input_b_sent",
            "survival_crafting_result_seen",
            "survival_crafting_result_collected",
            "survival_crafting_inventory_updated",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_survival_crafting_table_open",
            "server_survival_crafting_input_a",
            "server_survival_crafting_input_b",
            "server_survival_crafting_result",
            "server_survival_crafting_collect",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-survival-crafting-table-dry-run",
        dry_run_wrapper: "mc-compat-valence-survival-crafting-table",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "survival-biome-dimension-state",
        aliases: &["survival-biome-dimension-state"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "survival_biome_dimension_state",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_survival_biome_dimension_state",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason:
            "active survival-biome-dimension-parity Cairn owns dry-run wrapper and paired fixture promotion",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "mcp-controlled-smoke",
        aliases: &["mcp-controlled-smoke"],
        client_milestones: &[
            "mcp_initialize",
            "mcp_tools_list",
            "mcp_status_call",
            "mcp_command_outcomes",
        ],
        server_milestones: &[],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-mcp-controlled-smoke-dry-run",
        dry_run_wrapper: "mc-compat-mcp-controlled-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "combat-damage",
        aliases: &["combat-damage"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "remote_player_spawn",
            "combat_attack_sent",
            "combat_health_update",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_combat_damage",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-combat-damage-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-combat-damage",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "combat-knockback",
        aliases: &["combat-knockback"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "remote_player_spawn",
            "combat_attack_sent",
            "combat_health_update",
            "combat_velocity_update",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_combat_damage",
            "server_combat_knockback",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-combat-knockback-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-combat-knockback",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "armor-equipment-mitigation",
        aliases: &["armor-equipment-mitigation"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "remote_player_spawn",
            "armor_inventory_slot",
            "combat_attack_sent",
            "combat_health_update",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_equipment_state",
            "server_combat_damage",
            "server_armor_mitigation",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-armor-equipment-mitigation-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-armor-equipment-mitigation",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "equipment-update-observation",
        aliases: &["equipment-update-observation"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "remote_player_spawn",
            "entity_equipment_update",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_equipment_update_state",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-equipment-update-observation-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-equipment-update-observation",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "projectile-hit",
        aliases: &["projectile-hit"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "remote_player_spawn",
            "projectile_use_sent",
            "projectile_swing_sent",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_projectile_loadout",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-projectile-hit-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-projectile-hit",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "projectile-damage-attribution",
        aliases: &["projectile-damage-attribution"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "remote_player_spawn",
            "projectile_use_sent",
            "projectile_swing_sent",
            "projectile_damage_update",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_projectile_loadout",
            "server_projectile_use",
            "server_projectile_hit",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-projectile-damage-attribution-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-projectile-damage-attribution",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "flag-carrier-death-return",
        aliases: &["flag-carrier-death-return"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "team_blue",
            "flag_pickup",
            "remote_player_spawn",
            "combat_attack_sent",
            "combat_death_observed",
            "respawn_request_sent",
            "respawn_health_restored",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_flag_pickup",
            "server_flag_carrier_death",
            "server_flag_return",
        ],
        forbidden_patterns: FLAG_STATE_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-flag-carrier-death-return-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-flag-carrier-death-return",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "reconnect-flag-state",
        aliases: &["reconnect-flag-state"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "flag_pickup",
            "reconnect_session",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_flag_pickup",
            "server_flag_disconnect_return",
            "server_reconnect_state_coherent",
        ],
        forbidden_patterns: FLAG_STATE_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: TWO_SESSIONS,
        dry_run_check: "mc-compat-valence-ctf-reconnect-flag-state-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-reconnect-flag-state",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "ctf-invalid-pickup-ownership",
        aliases: &["ctf-invalid-pickup-ownership"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "ctf_invalid_pickup_attempted",
            "ctf_invalid_pickup_contained",
        ],
        server_milestones: &["server_username_seen", "server_invalid_pickup_rejected"],
        forbidden_patterns: &[
            "panic",
            "unexpected_eof",
            "protocol_mismatch",
            "decode_error",
            "unexpected_flag_pickup_chat",
            "unexpected_flag_pickup_milestone",
            "unexpected_server_flag_pickup",
            "unexpected_flag_capture",
            "unexpected_flag_capture_milestone",
            "unexpected_red_score",
            "unexpected_blue_score",
        ],
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-invalid-pickup-ownership-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-invalid-pickup-ownership",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "ctf-invalid-return-drop",
        aliases: &["ctf-invalid-return-drop"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "ctf_invalid_return_drop_attempted",
            "ctf_invalid_return_drop_contained",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_invalid_return_drop_rejected",
        ],
        forbidden_patterns: &[
            "panic",
            "unexpected_eof",
            "protocol_mismatch",
            "decode_error",
            "unexpected_flag_pickup_chat",
            "unexpected_server_flag_pickup",
            "unexpected_flag_return",
            "unexpected_flag_disconnect_return",
            "unexpected_flag_capture",
            "unexpected_flag_capture_milestone",
            "unexpected_red_score",
            "unexpected_blue_score",
        ],
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-invalid-return-drop-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-invalid-return-drop",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "ctf-score-limit-win-condition",
        aliases: &["ctf-score-limit-win-condition"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "flag_pickup",
            "flag_capture",
            "score_red_2",
            "ctf_score_limit_win_seen",
        ],
        server_milestones: &[
            "server_username_seen",
            "server_score_limit_pre_state",
            "server_score_limit_final_capture",
            "server_score_limit_win_condition",
        ],
        forbidden_patterns: &[
            "panic",
            "unexpected_eof",
            "protocol_mismatch",
            "decode_error",
            "score_limit_duplicate_win",
            "score_limit_post_win_score_mutation",
            "unexpected_red_score_3",
            "unexpected_blue_score_1",
        ],
        client_count: ONE_CLIENT,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-valence-ctf-score-limit-win-condition-dry-run",
        dry_run_wrapper: "mc-compat-valence-ctf-score-limit-win-condition",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "reconnect-flag-score",
        aliases: &["reconnect-flag-score"],
        client_milestones: &[
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "flag_pickup",
            "flag_capture",
            "score_red_1",
            "reconnect_session",
        ],
        server_milestones: &["server_username_seen", "server_flag_or_score"],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: ONE_CLIENT,
        session_count: TWO_SESSIONS,
        dry_run_check: "mc-compat-open-cairns-dry-run",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
    GeneratedScenarioRow {
        name: "multi-client-load-score",
        aliases: &["multi-client-load-score"],
        client_milestones: &[
            "multi_client_count",
            "protocol_detected",
            "join_game",
            "render_tick",
            "team_red",
            "flag_pickup",
            "flag_capture",
            "score_red_1",
        ],
        server_milestones: &[
            "server_client_a_seen",
            "server_client_b_seen",
            "server_flag_or_score",
        ],
        forbidden_patterns: DEFAULT_FORBIDDEN_PATTERNS,
        client_count: TWO_CLIENTS,
        session_count: ONE_SESSION,
        dry_run_check: "mc-compat-multi-client-scenario-dry-run",
        dry_run_wrapper: "mc-compat-smoke",
        dry_run_exclusion_reason: "",
        migration_state: "substring-fallback",
    },
];
